version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: postgres_tesis_db
    environment:
      POSTGRES_USER: principal
      POSTGRES_PASSWORD: DBTes1isP@assw0rdSt0ng0345
      POSTGRES_DB: postgres_db
    ports:
      - "5435:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: