export * from './BaseMovement.entity';
export * from './ComparativeMovement.entity';
export * from './ExcelFile.entity';
export * from './HistoricalComparison.entity';
export * from './Joint.entity';
export * from './Position.entity';
export * from './RecordingInstitution.entity';
export * from './User.entity';
export * from './VideoRecording.entity';
